runtime: php55
api_version: 1

handlers:

# Handle the main page by serving the index page.
- url: /$
  static_files: index.html
  upload: index.html
  secure: always

- url: /index.html(.*)$
  static_files: index.html
  upload: index.html
  secure: always

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /assets
  static_dir: assets


# Recommended file skipping declaration from the GAE tutorials
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?